#!/bin/sh

# Configure Traditional Chinese LuCI and the Taipei timezone on first boot.
uci -q set luci.main.lang='zh_tw'
uci -q set system.@system[0].hostname='AirPi-H5000M'
uci -q set system.@system[0].zonename='Asia/Taipei'
uci -q set system.@system[0].timezone='CST-8'
uci -q commit luci
uci -q commit system

exit 0

